# Generated by Django 6.0.2 on 2026-02-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_alter_profile_email_alter_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
    ]
